import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/cctv-maze/schema";

export const meta = {
  slug: "backs-path",
  title: "The Backs Path",
  difficulty: 4,
  publishedAt: new Date("2026-10-09T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  rows: 10,
  cols: 10,
  startRow: 6,
  startCol: 0,
  exitRow: 7,
  exitCol: 9,
  walls: [
    { row: 0, col: 2, side: "west" },
    { row: 0, col: 8, side: "west" },
    { row: 1, col: 1, side: "west" },
    { row: 1, col: 2, side: "west" },
    { row: 1, col: 3, side: "west" },
    { row: 1, col: 5, side: "west" },
    { row: 1, col: 5, side: "north" },
    { row: 1, col: 7, side: "west" },
    { row: 1, col: 7, side: "north" },
    { row: 1, col: 9, side: "west" },
    { row: 2, col: 2, side: "west" },
    { row: 2, col: 3, side: "west" },
    { row: 2, col: 3, side: "north" },
    { row: 2, col: 5, side: "west" },
    { row: 2, col: 6, side: "north" },
    { row: 2, col: 8, side: "west" },
    { row: 2, col: 8, side: "north" },
    { row: 3, col: 1, side: "west" },
    { row: 3, col: 1, side: "north" },
    { row: 3, col: 3, side: "west" },
    { row: 3, col: 5, side: "west" },
    { row: 3, col: 6, side: "north" },
    { row: 3, col: 7, side: "north" },
    { row: 3, col: 8, side: "west" },
    { row: 3, col: 9, side: "west" },
    { row: 4, col: 1, side: "west" },
    { row: 4, col: 2, side: "north" },
    { row: 4, col: 4, side: "west" },
    { row: 4, col: 4, side: "north" },
    { row: 4, col: 5, side: "north" },
    { row: 4, col: 6, side: "north" },
    { row: 4, col: 8, side: "west" },
    { row: 4, col: 9, side: "north" },
    { row: 5, col: 1, side: "west" },
    { row: 5, col: 2, side: "west" },
    { row: 5, col: 3, side: "north" },
    { row: 5, col: 4, side: "west" },
    { row: 5, col: 5, side: "north" },
    { row: 5, col: 6, side: "north" },
    { row: 5, col: 7, side: "west" },
    { row: 5, col: 7, side: "north" },
    { row: 5, col: 8, side: "north" },
    { row: 5, col: 9, side: "west" },
    { row: 6, col: 2, side: "north" },
    { row: 6, col: 3, side: "west" },
    { row: 6, col: 4, side: "north" },
    { row: 6, col: 5, side: "north" },
    { row: 6, col: 7, side: "west" },
    { row: 6, col: 8, side: "west" },
    { row: 6, col: 9, side: "west" },
    { row: 7, col: 1, side: "north" },
    { row: 7, col: 2, side: "west" },
    { row: 7, col: 3, side: "west" },
    { row: 7, col: 3, side: "north" },
    { row: 7, col: 4, side: "north" },
    { row: 7, col: 5, side: "north" },
    { row: 7, col: 6, side: "west" },
    { row: 7, col: 6, side: "north" },
    { row: 7, col: 8, side: "west" },
    { row: 8, col: 1, side: "west" },
    { row: 8, col: 3, side: "west" },
    { row: 8, col: 4, side: "west" },
    { row: 8, col: 4, side: "north" },
    { row: 8, col: 5, side: "west" },
    { row: 8, col: 6, side: "west" },
    { row: 8, col: 8, side: "north" },
    { row: 8, col: 9, side: "north" },
    { row: 9, col: 4, side: "west" },
    { row: 9, col: 6, side: "north" },
    { row: 9, col: 7, side: "north" },
    { row: 9, col: 8, side: "north" },
  ],
  cameras: [
    { row: 2, col: 0, facing: "nw", fovDeg: 90, rangeCells: 2 },
    { row: 8, col: 1, facing: "ne", fovDeg: 60, rangeCells: 5 },
    { row: 9, col: 4, facing: "nw", fovDeg: 45, rangeCells: 3 },
    { row: 7, col: 5, facing: "sw", fovDeg: 60, rangeCells: 5 },
    { row: 7, col: 2, facing: "se", fovDeg: 90, rangeCells: 6 },
    { row: 4, col: 5, facing: "s", fovDeg: 45, rangeCells: 5 },
    { row: 5, col: 5, facing: "s", fovDeg: 120, rangeCells: 4 },
  ],
} satisfies Content;
