import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/cctv-maze/schema";

export const meta = {
  slug: "kings-parade",
  title: "King's Parade",
  difficulty: 3,
  publishedAt: new Date("2026-10-09T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  rows: 8,
  cols: 9,
  startRow: 0,
  startCol: 0,
  exitRow: 5,
  exitCol: 8,
  walls: [
    { row: 0, col: 1, side: "west" },
    { row: 0, col: 7, side: "west" },
    { row: 1, col: 1, side: "west" },
    { row: 1, col: 1, side: "north" },
    { row: 1, col: 2, side: "north" },
    { row: 1, col: 4, side: "west" },
    { row: 1, col: 4, side: "north" },
    { row: 1, col: 5, side: "north" },
    { row: 1, col: 6, side: "west" },
    { row: 1, col: 8, side: "west" },
    { row: 2, col: 2, side: "west" },
    { row: 2, col: 2, side: "north" },
    { row: 2, col: 3, side: "north" },
    { row: 2, col: 5, side: "west" },
    { row: 2, col: 6, side: "west" },
    { row: 2, col: 8, side: "west" },
    { row: 3, col: 1, side: "west" },
    { row: 3, col: 2, side: "west" },
    { row: 3, col: 3, side: "west" },
    { row: 3, col: 3, side: "north" },
    { row: 3, col: 4, side: "west" },
    { row: 3, col: 4, side: "north" },
    { row: 3, col: 6, side: "west" },
    { row: 3, col: 6, side: "north" },
    { row: 3, col: 8, side: "north" },
    { row: 4, col: 1, side: "west" },
    { row: 4, col: 4, side: "west" },
    { row: 4, col: 5, side: "north" },
    { row: 4, col: 7, side: "west" },
    { row: 5, col: 1, side: "west" },
    { row: 5, col: 3, side: "north" },
    { row: 5, col: 4, side: "north" },
    { row: 5, col: 5, side: "west" },
    { row: 5, col: 5, side: "north" },
    { row: 5, col: 6, side: "north" },
    { row: 5, col: 8, side: "west" },
    { row: 6, col: 1, side: "west" },
    { row: 6, col: 2, side: "west" },
    { row: 6, col: 3, side: "north" },
    { row: 6, col: 4, side: "west" },
    { row: 6, col: 5, side: "west" },
    { row: 6, col: 6, side: "north" },
    { row: 6, col: 7, side: "north" },
    { row: 6, col: 8, side: "north" },
    { row: 7, col: 1, side: "north" },
    { row: 7, col: 4, side: "west" },
    { row: 7, col: 5, side: "north" },
    { row: 7, col: 6, side: "north" },
    { row: 7, col: 7, side: "north" },
  ],
  cameras: [
    { row: 1, col: 1, facing: "n", fovDeg: 45, rangeCells: 2 },
    { row: 0, col: 8, facing: "ne", fovDeg: 45, rangeCells: 4 },
    { row: 0, col: 2, facing: "se", fovDeg: 45, rangeCells: 5 },
    { row: 5, col: 1, facing: "nw", fovDeg: 45, rangeCells: 4 },
    { row: 2, col: 6, facing: "n", fovDeg: 45, rangeCells: 5 },
  ],
} satisfies Content;
