import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/cctv-maze/schema";

export const meta = {
  slug: "labyrinthos",
  title: "Labyrinthos",
  difficulty: 5,
  publishedAt: new Date("2026-10-09T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  rows: 12,
  cols: 12,
  startRow: 7,
  startCol: 0,
  exitRow: 6,
  exitCol: 11,
  walls: [
    { row: 0, col: 1, side: "west" },
    { row: 0, col: 5, side: "west" },
    { row: 0, col: 8, side: "west" },
    { row: 1, col: 1, side: "north" },
    { row: 1, col: 2, side: "west" },
    { row: 1, col: 3, side: "west" },
    { row: 1, col: 4, side: "west" },
    { row: 1, col: 4, side: "north" },
    { row: 1, col: 6, side: "west" },
    { row: 1, col: 7, side: "west" },
    { row: 1, col: 9, side: "west" },
    { row: 1, col: 10, side: "north" },
    { row: 1, col: 11, side: "north" },
    { row: 2, col: 0, side: "north" },
    { row: 2, col: 2, side: "west" },
    { row: 2, col: 3, side: "north" },
    { row: 2, col: 5, side: "west" },
    { row: 2, col: 7, side: "north" },
    { row: 2, col: 8, side: "north" },
    { row: 2, col: 9, side: "north" },
    { row: 2, col: 11, side: "west" },
    { row: 3, col: 1, side: "west" },
    { row: 3, col: 1, side: "north" },
    { row: 3, col: 2, side: "north" },
    { row: 3, col: 3, side: "west" },
    { row: 3, col: 4, side: "north" },
    { row: 3, col: 5, side: "north" },
    { row: 3, col: 6, side: "west" },
    { row: 3, col: 8, side: "north" },
    { row: 3, col: 10, side: "west" },
    { row: 3, col: 10, side: "north" },
    { row: 4, col: 2, side: "west" },
    { row: 4, col: 3, side: "north" },
    { row: 4, col: 4, side: "west" },
    { row: 4, col: 4, side: "north" },
    { row: 4, col: 5, side: "west" },
    { row: 4, col: 8, side: "west" },
    { row: 4, col: 9, side: "north" },
    { row: 4, col: 11, side: "west" },
    { row: 5, col: 0, side: "north" },
    { row: 5, col: 1, side: "north" },
    { row: 5, col: 2, side: "north" },
    { row: 5, col: 4, side: "west" },
    { row: 5, col: 5, side: "north" },
    { row: 5, col: 6, side: "west" },
    { row: 5, col: 8, side: "west" },
    { row: 5, col: 9, side: "west" },
    { row: 5, col: 9, side: "north" },
    { row: 5, col: 10, side: "north" },
    { row: 5, col: 11, side: "west" },
    { row: 6, col: 1, side: "west" },
    { row: 6, col: 1, side: "north" },
    { row: 6, col: 2, side: "north" },
    { row: 6, col: 3, side: "north" },
    { row: 6, col: 4, side: "north" },
    { row: 6, col: 6, side: "west" },
    { row: 6, col: 6, side: "north" },
    { row: 6, col: 8, side: "west" },
    { row: 6, col: 10, side: "west" },
    { row: 6, col: 11, side: "west" },
    { row: 7, col: 1, side: "west" },
    { row: 7, col: 2, side: "north" },
    { row: 7, col: 3, side: "north" },
    { row: 7, col: 4, side: "west" },
    { row: 7, col: 5, side: "west" },
    { row: 7, col: 5, side: "north" },
    { row: 7, col: 7, side: "west" },
    { row: 7, col: 7, side: "north" },
    { row: 7, col: 8, side: "west" },
    { row: 7, col: 8, side: "north" },
    { row: 7, col: 9, side: "north" },
    { row: 7, col: 10, side: "west" },
    { row: 7, col: 11, side: "west" },
    { row: 8, col: 1, side: "north" },
    { row: 8, col: 2, side: "north" },
    { row: 8, col: 3, side: "west" },
    { row: 8, col: 4, side: "west" },
    { row: 8, col: 6, side: "north" },
    { row: 8, col: 8, side: "west" },
    { row: 8, col: 9, side: "west" },
    { row: 8, col: 11, side: "west" },
    { row: 9, col: 1, side: "west" },
    { row: 9, col: 1, side: "north" },
    { row: 9, col: 3, side: "west" },
    { row: 9, col: 4, side: "west" },
    { row: 9, col: 4, side: "north" },
    { row: 9, col: 5, side: "north" },
    { row: 9, col: 6, side: "west" },
    { row: 9, col: 6, side: "north" },
    { row: 9, col: 8, side: "west" },
    { row: 9, col: 9, side: "west" },
    { row: 9, col: 9, side: "north" },
    { row: 9, col: 10, side: "north" },
    { row: 10, col: 1, side: "west" },
    { row: 10, col: 2, side: "west" },
    { row: 10, col: 2, side: "north" },
    { row: 10, col: 4, side: "west" },
    { row: 10, col: 5, side: "west" },
    { row: 10, col: 7, side: "north" },
    { row: 10, col: 9, side: "west" },
    { row: 10, col: 11, side: "north" },
    { row: 11, col: 2, side: "north" },
    { row: 11, col: 3, side: "north" },
    { row: 11, col: 6, side: "north" },
    { row: 11, col: 9, side: "west" },
    { row: 11, col: 9, side: "north" },
    { row: 11, col: 10, side: "north" },
  ],
  cameras: [
    { row: 3, col: 6, facing: "nw", fovDeg: 120, rangeCells: 5 },
    { row: 10, col: 1, facing: "ne", fovDeg: 90, rangeCells: 3 },
    { row: 8, col: 4, facing: "n", fovDeg: 90, rangeCells: 5 },
    { row: 0, col: 5, facing: "se", fovDeg: 120, rangeCells: 4 },
    { row: 11, col: 9, facing: "sw", fovDeg: 120, rangeCells: 3 },
    { row: 2, col: 2, facing: "ne", fovDeg: 90, rangeCells: 7 },
    { row: 3, col: 7, facing: "nw", fovDeg: 60, rangeCells: 3 },
    { row: 1, col: 2, facing: "sw", fovDeg: 90, rangeCells: 3 },
    { row: 0, col: 8, facing: "n", fovDeg: 120, rangeCells: 5 },
  ],
} satisfies Content;
