import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/cctv-maze/schema";

export const meta = {
  slug: "market-hill",
  title: "Market Hill",
  difficulty: 2,
  publishedAt: new Date("2026-10-09T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  rows: 7,
  cols: 8,
  startRow: 4,
  startCol: 0,
  exitRow: 0,
  exitCol: 7,
  walls: [
    { row: 0, col: 1, side: "west" },
    { row: 0, col: 5, side: "west" },
    { row: 1, col: 2, side: "north" },
    { row: 1, col: 3, side: "west" },
    { row: 1, col: 4, side: "west" },
    { row: 1, col: 6, side: "west" },
    { row: 1, col: 7, side: "north" },
    { row: 2, col: 0, side: "north" },
    { row: 2, col: 2, side: "west" },
    { row: 2, col: 3, side: "north" },
    { row: 2, col: 4, side: "west" },
    { row: 2, col: 5, side: "north" },
    { row: 2, col: 6, side: "north" },
    { row: 2, col: 7, side: "west" },
    { row: 3, col: 2, side: "north" },
    { row: 3, col: 3, side: "west" },
    { row: 3, col: 5, side: "west" },
    { row: 3, col: 5, side: "north" },
    { row: 3, col: 6, side: "west" },
    { row: 3, col: 7, side: "west" },
    { row: 4, col: 0, side: "north" },
    { row: 4, col: 2, side: "west" },
    { row: 4, col: 2, side: "north" },
    { row: 4, col: 3, side: "north" },
    { row: 4, col: 4, side: "north" },
    { row: 4, col: 5, side: "west" },
    { row: 4, col: 7, side: "west" },
    { row: 5, col: 1, side: "north" },
    { row: 5, col: 3, side: "west" },
    { row: 5, col: 4, side: "north" },
    { row: 5, col: 5, side: "west" },
    { row: 5, col: 6, side: "north" },
    { row: 6, col: 1, side: "north" },
    { row: 6, col: 3, side: "north" },
    { row: 6, col: 4, side: "west" },
    { row: 6, col: 5, side: "north" },
    { row: 6, col: 6, side: "north" },
  ],
  cameras: [
    { row: 1, col: 6, facing: "e", fovDeg: 45, rangeCells: 4 },
    { row: 2, col: 3, facing: "nw", fovDeg: 120, rangeCells: 5 },
    { row: 1, col: 3, facing: "nw", fovDeg: 45, rangeCells: 4 },
    { row: 3, col: 2, facing: "ne", fovDeg: 45, rangeCells: 2 },
  ],
} satisfies Content;
