import type * as core from "../src/db/schema/core";

type Category = typeof core.puzzleCategories.$inferInsert;
type PuzzleType = typeof core.puzzleTypes.$inferInsert;
type Volume = typeof core.volumes.$inferInsert;

export const categories = [
  { key: "flagship", name: "Flagship", sort: 1 },
  { key: "word", name: "Word", sort: 2 },
  { key: "logic", name: "Logic", sort: 3 },
  { key: "spatial", name: "Spatial", sort: 4 },
  { key: "cipher", name: "James's Notebooks", sort: 5 },
  { key: "numbers", name: "Numbers", sort: 6 },
] satisfies Category[];

export const types = [
  {
    key: "reverse-chess",
    categoryKey: "flagship",
    name: "Reverse Chess",
    description: "Work backwards from a position to the move that made it.",
    subtypeTable: "reverse_chess_puzzles",
    sort: 1,
  },
  {
    key: "rota",
    categoryKey: "flagship",
    name: "The Rota",
    description: "Unpick a swapped duty roster from the clues that remain.",
    subtypeTable: "rota_puzzles",
    sort: 2,
  },
  {
    key: "gears",
    categoryKey: "flagship",
    name: "The Gear Puzzle",
    description: "Turn the crank and find the gear that does not belong.",
    subtypeTable: "gear_puzzles",
    sort: 3,
  },
  {
    key: "crossword",
    categoryKey: "word",
    name: "Crossword",
    description: "Cryptic and quick crosswords with original clues.",
    subtypeTable: "crossword_puzzles",
    sort: 1,
  },
  {
    key: "anagram",
    categoryKey: "word",
    name: "Anagram",
    description: "Rearrange the letter tiles into a word or a phrase.",
    subtypeTable: "anagram_puzzles",
    sort: 2,
  },
  {
    key: "word-ladder",
    categoryKey: "word",
    name: "Word Ladder",
    description: "Change one letter per rung to climb from one word to another.",
    subtypeTable: "word_ladder_puzzles",
    sort: 3,
  },
  {
    key: "acrostic",
    categoryKey: "word",
    name: "Acrostic",
    description: "Read down the lines to find the hidden message.",
    subtypeTable: "acrostic_puzzles",
    sort: 4,
  },
  {
    key: "word-search",
    categoryKey: "word",
    name: "The Fob-Off",
    description: "Find every word hidden in the grid of letters.",
    subtypeTable: "word_search_puzzles",
    sort: 5,
  },
  {
    key: "logic-grid",
    categoryKey: "logic",
    name: "Logic Grid",
    description: "Match every item using only the clues, and spot a false one.",
    subtypeTable: "logic_grid_puzzles",
    sort: 1,
  },
  {
    key: "knights-knaves",
    categoryKey: "logic",
    name: "Knights and Knaves",
    description: "Decide who always tells the truth and who always lies.",
    subtypeTable: "knights_knaves_puzzles",
    sort: 2,
  },
  {
    key: "sudoku",
    categoryKey: "logic",
    name: "Sudoku",
    description: "Fill the 9 by 9 grid so no digit repeats.",
    subtypeTable: "sudoku_puzzles",
    sort: 3,
  },
  {
    key: "futoshiki",
    categoryKey: "logic",
    name: "Futoshiki",
    description: "Fill a 5 by 5 grid and obey the inequality signs.",
    subtypeTable: "futoshiki_puzzles",
    sort: 4,
  },
  {
    key: "odd-one-out",
    categoryKey: "logic",
    name: "Odd One Out",
    description: "Pick the item that breaks the pattern, and say why.",
    subtypeTable: "odd_one_out_puzzles",
    sort: 5,
  },
  {
    key: "sightlines",
    categoryKey: "spatial",
    name: "Sightlines",
    description: "Place pillars and observers, then mark the blind spots.",
    subtypeTable: "sightlines_puzzles",
    sort: 1,
  },
  {
    key: "cctv-maze",
    categoryKey: "spatial",
    name: "CCTV Maze",
    description: "Reach the exit without entering any camera's view.",
    subtypeTable: "cctv_maze_puzzles",
    sort: 2,
  },
  {
    key: "spot-difference",
    categoryKey: "spatial",
    name: "Spot the Difference",
    description: "Find every change between two near-identical scenes.",
    subtypeTable: "spot_difference_puzzles",
    sort: 3,
  },
  {
    key: "book-cipher",
    categoryKey: "cipher",
    name: "Book Cipher",
    description: "Decode page, line and word references into a message.",
    subtypeTable: "book_cipher_puzzles",
    sort: 1,
  },
  {
    key: "pictogram-cipher",
    categoryKey: "cipher",
    name: "Pictogram Cipher",
    description: "Crack a stick-figure alphabet one symbol at a time.",
    subtypeTable: "pictogram_cipher_puzzles",
    sort: 2,
  },
  {
    key: "caesar",
    categoryKey: "cipher",
    name: "Caesar Shift",
    description: "Undo the shift to read the plain message.",
    subtypeTable: "caesar_puzzles",
    sort: 3,
  },
  {
    key: "keyword",
    categoryKey: "cipher",
    name: "Keyword Cipher",
    description: "Recover the keyword and the message hidden behind it.",
    subtypeTable: "keyword_puzzles",
    sort: 4,
  },
  {
    key: "napkin-maths",
    categoryKey: "numbers",
    name: "Napkin Maths",
    description: "Deduce the missing figures from partial working.",
    subtypeTable: "napkin_maths_puzzles",
    sort: 1,
  },
] satisfies PuzzleType[];

export const volumes = [
  { slug: "pocket-collection-1", title: "Pocket Puzzle Collection 1", cover: "blue", sort: 1 },
  { slug: "pocket-collection-2", title: "Pocket Puzzle Collection 2", cover: "red", sort: 2 },
  { slug: "pocket-collection-3", title: "Pocket Puzzle Collection 3", cover: "ink", sort: 3 },
] satisfies Volume[];
