import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/crossword/schema";

export const meta = {
  slug: "fine-print",
  title: "Fine Print",
  difficulty: 4,
  publishedAt: new Date("2026-10-03T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  style: "cryptic",
  rows: 15,
  cols: 15,
  cells: [
    { row: 0, col: 0, letter: "S" }, { row: 0, col: 1, letter: "U" }, { row: 0, col: 2, letter: "S" }, { row: 0, col: 3, letter: "P" }, { row: 0, col: 4, letter: "E" }, { row: 0, col: 5, letter: "C" }, { row: 0, col: 6, letter: "T" }, { row: 0, col: 8, letter: "R" }, { row: 0, col: 9, letter: "E" }, { row: 0, col: 10, letter: "D" }, { row: 0, col: 11, letter: "T" }, { row: 0, col: 12, letter: "A" }, { row: 0, col: 13, letter: "P" }, { row: 0, col: 14, letter: "E" },
    { row: 1, col: 0, letter: "N" }, { row: 1, col: 2, letter: "W" }, { row: 1, col: 4, letter: "X" }, { row: 1, col: 6, letter: "R" }, { row: 1, col: 8, letter: "E" }, { row: 1, col: 10, letter: "I" }, { row: 1, col: 12, letter: "L" }, { row: 1, col: 14, letter: "N" },
    { row: 2, col: 0, letter: "A" }, { row: 2, col: 1, letter: "V" }, { row: 2, col: 2, letter: "E" }, { row: 2, col: 3, letter: "R" }, { row: 2, col: 4, letter: "A" }, { row: 2, col: 5, letter: "G" }, { row: 2, col: 6, letter: "E" }, { row: 2, col: 8, letter: "C" }, { row: 2, col: 9, letter: "U" }, { row: 2, col: 10, letter: "S" }, { row: 2, col: 11, letter: "T" }, { row: 2, col: 12, letter: "A" }, { row: 2, col: 13, letter: "R" }, { row: 2, col: 14, letter: "D" },
    { row: 3, col: 0, letter: "P" }, { row: 3, col: 2, letter: "A" }, { row: 3, col: 4, letter: "M" }, { row: 3, col: 6, letter: "A" }, { row: 3, col: 8, letter: "O" }, { row: 3, col: 10, letter: "C" }, { row: 3, col: 12, letter: "R" }, { row: 3, col: 14, letter: "A" },
    { row: 4, col: 0, letter: "P" }, { row: 4, col: 1, letter: "I" }, { row: 4, col: 2, letter: "T" }, { row: 4, col: 3, letter: "H" }, { row: 4, col: 5, letter: "S" }, { row: 4, col: 6, letter: "T" }, { row: 4, col: 7, letter: "O" }, { row: 4, col: 8, letter: "V" }, { row: 4, col: 9, letter: "E" }, { row: 4, col: 11, letter: "O" }, { row: 4, col: 12, letter: "M" }, { row: 4, col: 13, letter: "E" }, { row: 4, col: 14, letter: "N" },
    { row: 5, col: 0, letter: "Y" }, { row: 5, col: 2, letter: "S" }, { row: 5, col: 4, letter: "S" }, { row: 5, col: 6, letter: "Y" }, { row: 5, col: 8, letter: "E" }, { row: 5, col: 10, letter: "S" }, { row: 5, col: 14, letter: "G" },
    { row: 6, col: 1, letter: "T" }, { row: 6, col: 2, letter: "H" }, { row: 6, col: 3, letter: "I" }, { row: 6, col: 4, letter: "N" }, { row: 6, col: 5, letter: "K" }, { row: 6, col: 7, letter: "C" }, { row: 6, col: 8, letter: "R" }, { row: 6, col: 9, letter: "U" }, { row: 6, col: 10, letter: "C" }, { row: 6, col: 11, letter: "I" }, { row: 6, col: 12, letter: "B" }, { row: 6, col: 13, letter: "L" }, { row: 6, col: 14, letter: "E" },
    { row: 7, col: 0, letter: "I" }, { row: 7, col: 2, letter: "O" }, { row: 7, col: 4, letter: "O" }, { row: 7, col: 6, letter: "G" }, { row: 7, col: 8, letter: "Y" }, { row: 7, col: 10, letter: "A" }, { row: 7, col: 12, letter: "L" }, { row: 7, col: 14, letter: "R" },
    { row: 8, col: 0, letter: "C" }, { row: 8, col: 1, letter: "U" }, { row: 8, col: 2, letter: "P" }, { row: 8, col: 3, letter: "B" }, { row: 8, col: 4, letter: "O" }, { row: 8, col: 5, letter: "A" }, { row: 8, col: 6, letter: "R" }, { row: 8, col: 7, letter: "D" }, { row: 8, col: 9, letter: "T" }, { row: 8, col: 10, letter: "R" }, { row: 8, col: 11, letter: "O" }, { row: 8, col: 12, letter: "U" }, { row: 8, col: 13, letter: "T" },
    { row: 9, col: 0, letter: "E" }, { row: 9, col: 4, letter: "P" }, { row: 9, col: 6, letter: "A" }, { row: 9, col: 8, letter: "B" }, { row: 9, col: 10, letter: "E" }, { row: 9, col: 12, letter: "E" }, { row: 9, col: 14, letter: "S" },
    { row: 10, col: 0, letter: "C" }, { row: 10, col: 1, letter: "A" }, { row: 10, col: 2, letter: "S" }, { row: 10, col: 3, letter: "T" }, { row: 10, col: 5, letter: "A" }, { row: 10, col: 6, letter: "N" }, { row: 10, col: 7, letter: "G" }, { row: 10, col: 8, letter: "E" }, { row: 10, col: 9, letter: "L" }, { row: 10, col: 11, letter: "O" }, { row: 10, col: 12, letter: "B" }, { row: 10, col: 13, letter: "E" }, { row: 10, col: 14, letter: "Y" },
    { row: 11, col: 0, letter: "R" }, { row: 11, col: 2, letter: "T" }, { row: 11, col: 4, letter: "M" }, { row: 11, col: 6, letter: "D" }, { row: 11, col: 8, letter: "H" }, { row: 11, col: 10, letter: "U" }, { row: 11, col: 12, letter: "L" }, { row: 11, col: 14, letter: "S" },
    { row: 12, col: 0, letter: "E" }, { row: 12, col: 1, letter: "N" }, { row: 12, col: 2, letter: "E" }, { row: 12, col: 3, letter: "M" }, { row: 12, col: 4, letter: "I" }, { row: 12, col: 5, letter: "E" }, { row: 12, col: 6, letter: "S" }, { row: 12, col: 8, letter: "A" }, { row: 12, col: 9, letter: "I" }, { row: 12, col: 10, letter: "R" }, { row: 12, col: 11, letter: "P" }, { row: 12, col: 12, letter: "O" }, { row: 12, col: 13, letter: "R" }, { row: 12, col: 14, letter: "T" },
    { row: 13, col: 0, letter: "A" }, { row: 13, col: 2, letter: "I" }, { row: 13, col: 4, letter: "N" }, { row: 13, col: 6, letter: "O" }, { row: 13, col: 8, letter: "L" }, { row: 13, col: 10, letter: "G" }, { row: 13, col: 12, letter: "O" }, { row: 13, col: 14, letter: "E" },
    { row: 14, col: 0, letter: "M" }, { row: 14, col: 1, letter: "A" }, { row: 14, col: 2, letter: "N" }, { row: 14, col: 3, letter: "S" }, { row: 14, col: 4, letter: "I" }, { row: 14, col: 5, letter: "O" }, { row: 14, col: 6, letter: "N" }, { row: 14, col: 8, letter: "F" }, { row: 14, col: 9, letter: "R" }, { row: 14, col: 10, letter: "E" }, { row: 14, col: 11, letter: "E" }, { row: 14, col: 12, letter: "D" }, { row: 14, col: 13, letter: "O" }, { row: 14, col: 14, letter: "M" },
  ],
  clues: [
    { direction: "across", row: 0, col: 0, clueText: "Doubt, or one under investigation", segments: [7] },
    { direction: "down", row: 0, col: 0, clueText: "Small nappy? That's brisk", segments: [6] },
    { direction: "down", row: 0, col: 2, clueText: "Perspire, then store, in exploitative factory", segments: [9] },
    { direction: "down", row: 0, col: 4, clueText: "Old flame before noon: a test", segments: [4] },
    { direction: "down", row: 0, col: 6, clueText: "Spoil unknown to form an agreement", segments: [6] },
    { direction: "across", row: 0, col: 8, clueText: "Communist recording is bureaucratic hindrance", segments: [3, 4] },
    { direction: "down", row: 0, col: 8, clueText: "Get back yen, showing improvement in health", segments: [8] },
    { direction: "down", row: 0, col: 10, clueText: "Dance venue, losing nothing, gets a record", segments: [4] },
    { direction: "down", row: 0, col: 12, clueText: "A learner with limb gives warning", segments: [5] },
    { direction: "down", row: 0, col: 14, clueText: "Finish rage, so put at risk", segments: [8] },
    { direction: "across", row: 2, col: 0, clueText: "Declare era to be typical", segments: [7] },
    { direction: "across", row: 2, col: 8, clueText: "Dust car wrecked: it's layered in trifle", segments: [7] },
    { direction: "across", row: 4, col: 0, clueText: "Hole, with hospital, gives essence", segments: [4] },
    { direction: "across", row: 4, col: 5, clueText: "Votes wildly cast for a cooker", segments: [5] },
    { direction: "across", row: 4, col: 11, clueText: "Ring, then men: a portent", segments: [4] },
    { direction: "down", row: 5, col: 4, clueText: "Spoon, mixed up, to pry", segments: [5] },
    { direction: "down", row: 5, col: 10, clueText: "Small worry, but enough to frighten", segments: [5] },
    { direction: "across", row: 6, col: 1, clueText: "Thursday's writing fluid? Reflect", segments: [5] },
    { direction: "across", row: 6, col: 7, clueText: "Melting pot, or Miller's play", segments: [8] },
    { direction: "down", row: 6, col: 12, clueText: "Down plus gore makes a toff", segments: [4, 5] },
    { direction: "down", row: 7, col: 0, clueText: "Diamonds and the pick of the bunch make a cold dessert", segments: [3, 5] },
    { direction: "down", row: 7, col: 6, clueText: "Magnificent boy: a young relative", segments: [8] },
    { direction: "across", row: 8, col: 0, clueText: "Trophy, then climb aboard for kitchen storage", segments: [8] },
    { direction: "across", row: 8, col: 9, clueText: "Time and defeat for the fish", segments: [5] },
    { direction: "down", row: 9, col: 8, clueText: "Live with fifty per cent in another's interest", segments: [6] },
    { direction: "down", row: 9, col: 14, clueText: "Small unknown plant stalk: method", segments: [6] },
    { direction: "across", row: 10, col: 0, clueText: "Throw the actors", segments: [4] },
    { direction: "down", row: 10, col: 2, clueText: "Saint with German one: a beer mug", segments: [5] },
    { direction: "across", row: 10, col: 5, clueText: "Glean, in a mess, a heavenly messenger", segments: [5] },
    { direction: "across", row: 10, col: 11, clueText: "Old, to exist, unknown: comply", segments: [4] },
    { direction: "down", row: 11, col: 4, clueText: "Small car, or skirt", segments: [4] },
    { direction: "down", row: 11, col: 10, clueText: "Desire found in surgeon", segments: [4] },
    { direction: "across", row: 12, col: 0, clueText: "I see men scattered: they're opponents", segments: [7] },
    { direction: "across", row: 12, col: 8, clueText: "Broadcast wine at terminal", segments: [7] },
    { direction: "across", row: 14, col: 0, clueText: "Fellow, second, charged particle: big house", segments: [7] },
    { direction: "across", row: 14, col: 8, clueText: "Released, with Order of Merit: liberty", segments: [7] },
  ],
} satisfies Content;
