import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/crossword/schema";

export const meta = {
  slug: "fresh-ink",
  title: "Fresh Ink",
  difficulty: 1,
  publishedAt: new Date("2026-10-01T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  style: "quick",
  rows: 11,
  cols: 11,
  cells: [
    { row: 0, col: 1, letter: "P" }, { row: 0, col: 2, letter: "A" }, { row: 0, col: 3, letter: "G" }, { row: 0, col: 4, letter: "E" }, { row: 0, col: 8, letter: "H" }, { row: 0, col: 9, letter: "I" }, { row: 0, col: 10, letter: "P" },
    { row: 1, col: 0, letter: "C" }, { row: 1, col: 1, letter: "A" }, { row: 1, col: 2, letter: "M" }, { row: 1, col: 3, letter: "E" }, { row: 1, col: 4, letter: "R" }, { row: 1, col: 5, letter: "A" }, { row: 1, col: 7, letter: "G" }, { row: 1, col: 8, letter: "E" }, { row: 1, col: 9, letter: "N" }, { row: 1, col: 10, letter: "E" },
    { row: 2, col: 0, letter: "A" }, { row: 2, col: 1, letter: "N" }, { row: 2, col: 2, letter: "I" }, { row: 2, col: 3, letter: "M" }, { row: 2, col: 4, letter: "A" }, { row: 2, col: 5, letter: "L" }, { row: 2, col: 7, letter: "R" }, { row: 2, col: 8, letter: "A" }, { row: 2, col: 9, letter: "V" }, { row: 2, col: 10, letter: "E" },
    { row: 3, col: 0, letter: "R" }, { row: 3, col: 1, letter: "E" }, { row: 3, col: 2, letter: "D" }, { row: 3, col: 5, letter: "T" }, { row: 3, col: 6, letter: "R" }, { row: 3, col: 7, letter: "A" }, { row: 3, col: 8, letter: "V" }, { row: 3, col: 9, letter: "E" }, { row: 3, col: 10, letter: "L" },
    { row: 4, col: 4, letter: "W" }, { row: 4, col: 5, letter: "O" }, { row: 4, col: 6, letter: "O" }, { row: 4, col: 7, letter: "D" }, { row: 4, col: 8, letter: "E" }, { row: 4, col: 9, letter: "N" },
    { row: 5, col: 1, letter: "L" }, { row: 5, col: 2, letter: "I" }, { row: 5, col: 3, letter: "A" }, { row: 5, col: 4, letter: "R" }, { row: 5, col: 6, letter: "D" }, { row: 5, col: 7, letter: "E" }, { row: 5, col: 8, letter: "N" }, { row: 5, col: 9, letter: "T" },
    { row: 6, col: 1, letter: "I" }, { row: 6, col: 2, letter: "N" }, { row: 6, col: 3, letter: "S" }, { row: 6, col: 4, letter: "I" }, { row: 6, col: 5, letter: "D" }, { row: 6, col: 6, letter: "E" },
    { row: 7, col: 0, letter: "I" }, { row: 7, col: 1, letter: "N" }, { row: 7, col: 2, letter: "V" }, { row: 7, col: 3, letter: "I" }, { row: 7, col: 4, letter: "T" }, { row: 7, col: 5, letter: "E" }, { row: 7, col: 8, letter: "P" }, { row: 7, col: 9, letter: "U" }, { row: 7, col: 10, letter: "B" },
    { row: 8, col: 0, letter: "D" }, { row: 8, col: 1, letter: "E" }, { row: 8, col: 2, letter: "E" }, { row: 8, col: 3, letter: "D" }, { row: 8, col: 5, letter: "B" }, { row: 8, col: 6, letter: "E" }, { row: 8, col: 7, letter: "F" }, { row: 8, col: 8, letter: "O" }, { row: 8, col: 9, letter: "R" }, { row: 8, col: 10, letter: "E" },
    { row: 9, col: 0, letter: "E" }, { row: 9, col: 1, letter: "A" }, { row: 9, col: 2, letter: "S" }, { row: 9, col: 3, letter: "E" }, { row: 9, col: 5, letter: "T" }, { row: 9, col: 6, letter: "A" }, { row: 9, col: 7, letter: "L" }, { row: 9, col: 8, letter: "E" }, { row: 9, col: 9, letter: "N" }, { row: 9, col: 10, letter: "T" },
    { row: 10, col: 0, letter: "A" }, { row: 10, col: 1, letter: "R" }, { row: 10, col: 2, letter: "T" }, { row: 10, col: 6, letter: "R" }, { row: 10, col: 7, letter: "U" }, { row: 10, col: 8, letter: "T" }, { row: 10, col: 9, letter: "S" },
  ],
  clues: [
    { direction: "across", row: 0, col: 1, clueText: "One side of a leaf in a book", segments: [4] },
    { direction: "down", row: 0, col: 1, clueText: "Sheet of glass in a window", segments: [4] },
    { direction: "down", row: 0, col: 2, clueText: "In the middle of", segments: [4] },
    { direction: "down", row: 0, col: 3, clueText: "Cut and polished jewel", segments: [3] },
    { direction: "down", row: 0, col: 4, clueText: "Period of history", segments: [3] },
    { direction: "across", row: 0, col: 8, clueText: "Joint at the top of the leg", segments: [3] },
    { direction: "down", row: 0, col: 8, clueText: "Paradise", segments: [6] },
    { direction: "down", row: 0, col: 9, clueText: "Come up with something new", segments: [6] },
    { direction: "down", row: 0, col: 10, clueText: "Skin of an orange", segments: [4] },
    { direction: "across", row: 1, col: 0, clueText: "Device for taking photographs", segments: [6] },
    { direction: "down", row: 1, col: 0, clueText: "Motor vehicle", segments: [3] },
    { direction: "down", row: 1, col: 5, clueText: "Singing voice lower than a soprano", segments: [4] },
    { direction: "across", row: 1, col: 7, clueText: "Part of the DNA passed from parent to child", segments: [4] },
    { direction: "down", row: 1, col: 7, clueText: "Mark on a test paper", segments: [5] },
    { direction: "across", row: 2, col: 0, clueText: "Dog, cat or horse", segments: [6] },
    { direction: "across", row: 2, col: 7, clueText: "Glowing review, or a lively party", segments: [4] },
    { direction: "across", row: 3, col: 0, clueText: "Colour of a pillar box", segments: [3] },
    { direction: "across", row: 3, col: 5, clueText: "Go on journeys", segments: [6] },
    { direction: "down", row: 3, col: 6, clueText: "Travelled on horseback", segments: [4] },
    { direction: "across", row: 4, col: 4, clueText: "Made from timber", segments: [6] },
    { direction: "down", row: 4, col: 4, clueText: "Legal order from a court", segments: [4] },
    { direction: "across", row: 5, col: 1, clueText: "One who does not tell the truth", segments: [4] },
    { direction: "down", row: 5, col: 1, clueText: "In a straight line", segments: [6] },
    { direction: "down", row: 5, col: 2, clueText: "Put money in, hoping for profit", segments: [6] },
    { direction: "down", row: 5, col: 3, clueText: "Remark made to the audience, or to one side", segments: [5] },
    { direction: "across", row: 5, col: 6, clueText: "Hollow left by a knock", segments: [4] },
    { direction: "across", row: 6, col: 1, clueText: "Within", segments: [6] },
    { direction: "down", row: 6, col: 5, clueText: "Money owed", segments: [4] },
    { direction: "across", row: 7, col: 0, clueText: "Ask to a party", segments: [6] },
    { direction: "down", row: 7, col: 0, clueText: "Brainwave", segments: [4] },
    { direction: "across", row: 7, col: 8, clueText: "Place to drink beer", segments: [3] },
    { direction: "down", row: 7, col: 8, clueText: "Writer of verse", segments: [4] },
    { direction: "down", row: 7, col: 9, clueText: "Vases for ashes", segments: [4] },
    { direction: "down", row: 7, col: 10, clueText: "Wager", segments: [3] },
    { direction: "across", row: 8, col: 0, clueText: "Heroic act", segments: [4] },
    { direction: "across", row: 8, col: 5, clueText: "Earlier than", segments: [6] },
    { direction: "down", row: 8, col: 6, clueText: "Organ of hearing", segments: [3] },
    { direction: "down", row: 8, col: 7, clueText: "Illness with fever and aches", segments: [3] },
    { direction: "across", row: 9, col: 0, clueText: "Make less painful", segments: [4] },
    { direction: "across", row: 9, col: 5, clueText: "Natural gift", segments: [6] },
    { direction: "across", row: 10, col: 0, clueText: "Painting or sculpture", segments: [3] },
    { direction: "across", row: 10, col: 6, clueText: "Grooves worn into a track", segments: [4] },
  ],
} satisfies Content;
