import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/crossword/schema";

export const meta = {
  slug: "loose-ends",
  title: "Loose Ends",
  difficulty: 3,
  publishedAt: new Date("2026-10-03T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  style: "cryptic",
  rows: 13,
  cols: 13,
  cells: [
    { row: 0, col: 0, letter: "S" }, { row: 0, col: 1, letter: "I" }, { row: 0, col: 2, letter: "S" }, { row: 0, col: 3, letter: "T" }, { row: 0, col: 4, letter: "E" }, { row: 0, col: 5, letter: "R" }, { row: 0, col: 7, letter: "B" }, { row: 0, col: 8, letter: "A" }, { row: 0, col: 9, letter: "N" }, { row: 0, col: 10, letter: "N" }, { row: 0, col: 11, letter: "E" }, { row: 0, col: 12, letter: "R" },
    { row: 1, col: 0, letter: "U" }, { row: 1, col: 2, letter: "E" }, { row: 1, col: 4, letter: "N" }, { row: 1, col: 6, letter: "P" }, { row: 1, col: 8, letter: "I" }, { row: 1, col: 10, letter: "O" }, { row: 1, col: 12, letter: "A" },
    { row: 2, col: 0, letter: "B" }, { row: 2, col: 1, letter: "R" }, { row: 2, col: 2, letter: "A" }, { row: 2, col: 3, letter: "S" }, { row: 2, col: 4, letter: "S" }, { row: 2, col: 5, letter: "B" }, { row: 2, col: 6, letter: "A" }, { row: 2, col: 7, letter: "N" }, { row: 2, col: 8, letter: "D" }, { row: 2, col: 10, letter: "S" }, { row: 2, col: 11, letter: "I" }, { row: 2, col: 12, letter: "T" },
    { row: 3, col: 0, letter: "M" }, { row: 3, col: 4, letter: "E" }, { row: 3, col: 6, letter: "R" }, { row: 3, col: 8, letter: "E" }, { row: 3, col: 10, letter: "E" }, { row: 3, col: 12, letter: "H" },
    { row: 4, col: 0, letter: "I" }, { row: 4, col: 1, letter: "N" }, { row: 4, col: 2, letter: "T" }, { row: 4, col: 3, letter: "I" }, { row: 4, col: 4, letter: "M" }, { row: 4, col: 5, letter: "A" }, { row: 4, col: 6, letter: "T" }, { row: 4, col: 7, letter: "E" }, { row: 4, col: 9, letter: "A" }, { row: 4, col: 10, letter: "B" }, { row: 4, col: 11, letter: "L" }, { row: 4, col: 12, letter: "E" },
    { row: 5, col: 0, letter: "T" }, { row: 5, col: 2, letter: "H" }, { row: 5, col: 4, letter: "B" }, { row: 5, col: 6, letter: "Y" }, { row: 5, col: 8, letter: "T" }, { row: 5, col: 10, letter: "L" }, { row: 5, col: 12, letter: "R" },
    { row: 6, col: 1, letter: "B" }, { row: 6, col: 2, letter: "U" }, { row: 6, col: 3, letter: "I" }, { row: 6, col: 4, letter: "L" }, { row: 6, col: 5, letter: "T" }, { row: 6, col: 7, letter: "T" }, { row: 6, col: 8, letter: "E" }, { row: 6, col: 9, letter: "N" }, { row: 6, col: 10, letter: "E" }, { row: 6, col: 11, letter: "T" },
    { row: 7, col: 0, letter: "C" }, { row: 7, col: 2, letter: "M" }, { row: 7, col: 4, letter: "E" }, { row: 7, col: 6, letter: "E" }, { row: 7, col: 8, letter: "A" }, { row: 7, col: 10, letter: "E" }, { row: 7, col: 12, letter: "E" },
    { row: 8, col: 0, letter: "R" }, { row: 8, col: 1, letter: "U" }, { row: 8, col: 2, letter: "B" }, { row: 8, col: 3, letter: "Y" }, { row: 8, col: 5, letter: "W" }, { row: 8, col: 6, letter: "A" }, { row: 8, col: 7, letter: "T" }, { row: 8, col: 8, letter: "C" }, { row: 8, col: 9, letter: "H" }, { row: 8, col: 10, letter: "D" }, { row: 8, col: 11, letter: "O" }, { row: 8, col: 12, letter: "G" },
    { row: 9, col: 0, letter: "I" }, { row: 9, col: 2, letter: "N" }, { row: 9, col: 4, letter: "P" }, { row: 9, col: 6, letter: "R" }, { row: 9, col: 8, letter: "H" }, { row: 9, col: 12, letter: "G" },
    { row: 10, col: 0, letter: "S" }, { row: 10, col: 1, letter: "P" }, { row: 10, col: 2, letter: "A" }, { row: 10, col: 4, letter: "A" }, { row: 10, col: 5, letter: "U" }, { row: 10, col: 6, letter: "T" }, { row: 10, col: 7, letter: "H" }, { row: 10, col: 8, letter: "E" }, { row: 10, col: 9, letter: "N" }, { row: 10, col: 10, letter: "T" }, { row: 10, col: 11, letter: "I" }, { row: 10, col: 12, letter: "C" },
    { row: 11, col: 0, letter: "I" }, { row: 11, col: 2, letter: "I" }, { row: 11, col: 4, letter: "I" }, { row: 11, col: 6, letter: "H" }, { row: 11, col: 8, letter: "R" }, { row: 11, col: 10, letter: "O" }, { row: 11, col: 12, letter: "U" },
    { row: 12, col: 0, letter: "S" }, { row: 12, col: 1, letter: "I" }, { row: 12, col: 2, letter: "L" }, { row: 12, col: 3, letter: "E" }, { row: 12, col: 4, letter: "N" }, { row: 12, col: 5, letter: "T" }, { row: 12, col: 7, letter: "A" }, { row: 12, col: 8, letter: "S" }, { row: 12, col: 9, letter: "L" }, { row: 12, col: 10, letter: "E" }, { row: 12, col: 11, letter: "E" }, { row: 12, col: 12, letter: "P" },
  ],
  clues: [
    { direction: "across", row: 0, col: 0, clueText: "Resist, mixed up, that's a sibling", segments: [6] },
    { direction: "down", row: 0, col: 0, clueText: "Surrender, as Tim and bus are scrambled", segments: [6] },
    { direction: "down", row: 0, col: 2, clueText: "Perceive, they say, the main", segments: [3] },
    { direction: "down", row: 0, col: 4, clueText: "Outfit or group of musicians", segments: [8] },
    { direction: "across", row: 0, col: 7, clueText: "Flag, or one who prohibits", segments: [6] },
    { direction: "down", row: 0, col: 8, clueText: "Help English: assistant", segments: [4] },
    { direction: "down", row: 0, col: 10, clueText: "Snoop, then extort: facial haemorrhage", segments: [9] },
    { direction: "down", row: 0, col: 12, clueText: "Traitor, with her, to some extent", segments: [6] },
    { direction: "down", row: 1, col: 6, clueText: "Part, then unknown quantity: it's a do", segments: [5] },
    { direction: "across", row: 2, col: 0, clueText: "Cheek and group form something heard on parade", segments: [5, 4] },
    { direction: "across", row: 2, col: 10, clueText: "Son's got it, so takes a seat", segments: [3] },
    { direction: "across", row: 4, col: 0, clueText: "Suggest something close", segments: [8] },
    { direction: "down", row: 4, col: 2, clueText: "Digit's cover, or tiny image", segments: [9] },
    { direction: "across", row: 4, col: 9, clueText: "A bachelor, with the French, is capable", segments: [4] },
    { direction: "down", row: 5, col: 8, clueText: "Cheaters cunningly turned into instructors", segments: [8] },
    { direction: "across", row: 6, col: 1, clueText: "Rebuilt, losing about, constructed", segments: [5] },
    { direction: "across", row: 6, col: 7, clueText: "Number plus extraterrestrial makes principle", segments: [5] },
    { direction: "down", row: 7, col: 0, clueText: "Chromium and the Thames at Oxford making emergency", segments: [6] },
    { direction: "down", row: 7, col: 6, clueText: "Heart, shattered, produces the planet", segments: [5] },
    { direction: "down", row: 7, col: 12, clueText: "Urge on, then trophy for breakfast holder", segments: [3, 3] },
    { direction: "across", row: 8, col: 0, clueText: "Polish unknown gem", segments: [4] },
    { direction: "across", row: 8, col: 5, clueText: "Look, then follow, as guardian", segments: [8] },
    { direction: "down", row: 9, col: 4, clueText: "Father at home: suffering", segments: [4] },
    { direction: "across", row: 10, col: 0, clueText: "Son's dad finds health resort", segments: [3] },
    { direction: "across", row: 10, col: 4, clueText: "A posh, at that time, twitch: genuine", segments: [9] },
    { direction: "down", row: 10, col: 10, clueText: "Part of foot to pull, we hear", segments: [3] },
    { direction: "across", row: 12, col: 0, clueText: "Quiet: son, one, loaned", segments: [6] },
    { direction: "across", row: 12, col: 7, clueText: "Please rearranged: in the land of nod", segments: [6] },
  ],
} satisfies Content;
