import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/crossword/schema";

export const meta = {
  slug: "margin-notes",
  title: "Margin Notes",
  difficulty: 2,
  publishedAt: new Date("2026-10-01T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  style: "quick",
  rows: 11,
  cols: 11,
  cells: [
    { row: 0, col: 1, letter: "L" }, { row: 0, col: 2, letter: "I" }, { row: 0, col: 3, letter: "T" }, { row: 0, col: 6, letter: "T" }, { row: 0, col: 7, letter: "S" }, { row: 0, col: 8, letter: "A" }, { row: 0, col: 9, letter: "R" },
    { row: 1, col: 0, letter: "T" }, { row: 1, col: 1, letter: "U" }, { row: 1, col: 2, letter: "N" }, { row: 1, col: 3, letter: "E" }, { row: 1, col: 6, letter: "O" }, { row: 1, col: 7, letter: "C" }, { row: 1, col: 8, letter: "T" }, { row: 1, col: 9, letter: "E" }, { row: 1, col: 10, letter: "T" },
    { row: 2, col: 0, letter: "A" }, { row: 2, col: 1, letter: "R" }, { row: 2, col: 2, letter: "E" }, { row: 2, col: 3, letter: "A" }, { row: 2, col: 5, letter: "W" }, { row: 2, col: 6, letter: "E" }, { row: 2, col: 7, letter: "A" }, { row: 2, col: 8, letter: "L" }, { row: 2, col: 9, letter: "T" }, { row: 2, col: 10, letter: "H" },
    { row: 3, col: 0, letter: "P" }, { row: 3, col: 1, letter: "E" }, { row: 3, col: 2, letter: "P" }, { row: 3, col: 3, letter: "P" }, { row: 3, col: 4, letter: "E" }, { row: 3, col: 5, letter: "R" }, { row: 3, col: 7, letter: "R" }, { row: 3, col: 8, letter: "A" }, { row: 3, col: 9, letter: "R" }, { row: 3, col: 10, letter: "E" },
    { row: 4, col: 2, letter: "T" }, { row: 4, col: 3, letter: "O" }, { row: 4, col: 4, letter: "R" }, { row: 4, col: 5, letter: "E" }, { row: 4, col: 8, letter: "S" }, { row: 4, col: 9, letter: "O" }, { row: 4, col: 10, letter: "N" },
    { row: 5, col: 3, letter: "T" }, { row: 5, col: 4, letter: "A" }, { row: 5, col: 5, letter: "S" }, { row: 5, col: 6, letter: "T" }, { row: 5, col: 7, letter: "E" },
    { row: 6, col: 0, letter: "W" }, { row: 6, col: 1, letter: "O" }, { row: 6, col: 2, letter: "W" }, { row: 6, col: 5, letter: "T" }, { row: 6, col: 6, letter: "E" }, { row: 6, col: 7, letter: "N" }, { row: 6, col: 8, letter: "S" },
    { row: 7, col: 0, letter: "A" }, { row: 7, col: 1, letter: "T" }, { row: 7, col: 2, letter: "O" }, { row: 7, col: 3, letter: "M" }, { row: 7, col: 5, letter: "L" }, { row: 7, col: 6, letter: "A" }, { row: 7, col: 7, letter: "T" }, { row: 7, col: 8, letter: "E" }, { row: 7, col: 9, letter: "L" }, { row: 7, col: 10, letter: "Y" },
    { row: 8, col: 0, letter: "S" }, { row: 8, col: 1, letter: "T" }, { row: 8, col: 2, letter: "R" }, { row: 8, col: 3, letter: "I" }, { row: 8, col: 4, letter: "P" }, { row: 8, col: 5, letter: "E" }, { row: 8, col: 7, letter: "I" }, { row: 8, col: 8, letter: "D" }, { row: 8, col: 9, letter: "E" }, { row: 8, col: 10, letter: "A" },
    { row: 9, col: 0, letter: "P" }, { row: 9, col: 1, letter: "E" }, { row: 9, col: 2, letter: "S" }, { row: 9, col: 3, letter: "T" }, { row: 9, col: 4, letter: "O" }, { row: 9, col: 7, letter: "R" }, { row: 9, col: 8, letter: "A" }, { row: 9, col: 9, letter: "N" }, { row: 9, col: 10, letter: "K" },
    { row: 10, col: 1, letter: "R" }, { row: 10, col: 2, letter: "E" }, { row: 10, col: 3, letter: "E" }, { row: 10, col: 4, letter: "D" }, { row: 10, col: 7, letter: "E" }, { row: 10, col: 8, letter: "N" }, { row: 10, col: 9, letter: "D" },
  ],
  clues: [
    { direction: "across", row: 0, col: 1, clueText: "Set alight", segments: [3] },
    { direction: "down", row: 0, col: 1, clueText: "Bait", segments: [4] },
    { direction: "down", row: 0, col: 2, clueText: "Clumsy", segments: [5] },
    { direction: "down", row: 0, col: 3, clueText: "Vessel for pouring a brew", segments: [6] },
    { direction: "across", row: 0, col: 6, clueText: "Former Russian emperor", segments: [4] },
    { direction: "down", row: 0, col: 6, clueText: "Part of the foot", segments: [3] },
    { direction: "down", row: 0, col: 7, clueText: "Mark left by a healed wound", segments: [4] },
    { direction: "down", row: 0, col: 8, clueText: "Book of maps", segments: [5] },
    { direction: "down", row: 0, col: 9, clueText: "Deliberately old-fashioned", segments: [5] },
    { direction: "across", row: 1, col: 0, clueText: "Melody", segments: [4] },
    { direction: "down", row: 1, col: 0, clueText: "Light knock on a door", segments: [3] },
    { direction: "across", row: 1, col: 6, clueText: "Group of eight", segments: [5] },
    { direction: "down", row: 1, col: 10, clueText: "At that time", segments: [4] },
    { direction: "across", row: 2, col: 0, clueText: "Size of a surface", segments: [4] },
    { direction: "across", row: 2, col: 5, clueText: "Riches", segments: [6] },
    { direction: "down", row: 2, col: 5, clueText: "Grapple with an opponent", segments: [7] },
    { direction: "across", row: 3, col: 0, clueText: "Spice ground at the table", segments: [6] },
    { direction: "down", row: 3, col: 4, clueText: "Age", segments: [3] },
    { direction: "across", row: 3, col: 7, clueText: "Seldom found, or lightly cooked", segments: [4] },
    { direction: "across", row: 4, col: 2, clueText: "Ripped", segments: [4] },
    { direction: "across", row: 4, col: 8, clueText: "Male child", segments: [3] },
    { direction: "across", row: 5, col: 3, clueText: "Sample with the tongue", segments: [5] },
    { direction: "down", row: 5, col: 6, clueText: "Afternoon drink", segments: [3] },
    { direction: "down", row: 5, col: 7, clueText: "Complete", segments: [6] },
    { direction: "across", row: 6, col: 0, clueText: "Cry of amazement", segments: [3] },
    { direction: "down", row: 6, col: 0, clueText: "Striped stinging insect", segments: [4] },
    { direction: "down", row: 6, col: 1, clueText: "River animal that floats on its back", segments: [5] },
    { direction: "down", row: 6, col: 2, clueText: "More terrible", segments: [5] },
    { direction: "across", row: 6, col: 5, clueText: "Numbers after nine", segments: [4] },
    { direction: "down", row: 6, col: 8, clueText: "Four-door saloon car", segments: [5] },
    { direction: "across", row: 7, col: 0, clueText: "Smallest unit of an element", segments: [4] },
    { direction: "down", row: 7, col: 3, clueText: "Tiny creature related to the spider", segments: [4] },
    { direction: "across", row: 7, col: 5, clueText: "Recently", segments: [6] },
    { direction: "down", row: 7, col: 9, clueText: "Let someone borrow", segments: [4] },
    { direction: "down", row: 7, col: 10, clueText: "Shaggy ox of the high Himalayas", segments: [3] },
    { direction: "across", row: 8, col: 0, clueText: "Band of colour", segments: [6] },
    { direction: "down", row: 8, col: 4, clueText: "Case that holds peas", segments: [3] },
    { direction: "across", row: 8, col: 7, clueText: "Plan or notion", segments: [4] },
    { direction: "across", row: 9, col: 0, clueText: "Green Italian sauce made with basil", segments: [5] },
    { direction: "across", row: 9, col: 7, clueText: "Position in the army", segments: [4] },
    { direction: "across", row: 10, col: 1, clueText: "Tall plant growing by water", segments: [4] },
    { direction: "across", row: 10, col: 7, clueText: "Finish", segments: [3] },
  ],
} satisfies Content;
