import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/crossword/schema";

export const meta = {
  slug: "paper-round",
  title: "Paper Round",
  difficulty: 2,
  publishedAt: new Date("2026-10-01T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  style: "quick",
  rows: 11,
  cols: 11,
  cells: [
    { row: 0, col: 0, letter: "B" }, { row: 0, col: 1, letter: "A" }, { row: 0, col: 2, letter: "K" }, { row: 0, col: 3, letter: "E" }, { row: 0, col: 6, letter: "C" }, { row: 0, col: 7, letter: "U" }, { row: 0, col: 8, letter: "T" },
    { row: 1, col: 0, letter: "E" }, { row: 1, col: 1, letter: "X" }, { row: 1, col: 2, letter: "I" }, { row: 1, col: 3, letter: "S" }, { row: 1, col: 4, letter: "T" }, { row: 1, col: 6, letter: "A" }, { row: 1, col: 7, letter: "S" }, { row: 1, col: 8, letter: "H" }, { row: 1, col: 9, letter: "E" }, { row: 1, col: 10, letter: "N" },
    { row: 2, col: 0, letter: "D" }, { row: 2, col: 1, letter: "E" }, { row: 2, col: 2, letter: "L" }, { row: 2, col: 3, letter: "T" }, { row: 2, col: 4, letter: "A" }, { row: 2, col: 6, letter: "N" }, { row: 2, col: 7, letter: "E" }, { row: 2, col: 8, letter: "R" }, { row: 2, col: 9, letter: "V" }, { row: 2, col: 10, letter: "E" },
    { row: 3, col: 1, letter: "S" }, { row: 3, col: 2, letter: "T" }, { row: 3, col: 3, letter: "A" }, { row: 3, col: 4, letter: "R" }, { row: 3, col: 5, letter: "T" }, { row: 3, col: 7, letter: "D" }, { row: 3, col: 8, letter: "E" }, { row: 3, col: 9, letter: "E" }, { row: 3, col: 10, letter: "R" },
    { row: 4, col: 3, letter: "T" }, { row: 4, col: 4, letter: "O" }, { row: 4, col: 5, letter: "Y" }, { row: 4, col: 8, letter: "A" }, { row: 4, col: 9, letter: "N" }, { row: 4, col: 10, letter: "D" },
    { row: 5, col: 2, letter: "R" }, { row: 5, col: 3, letter: "E" }, { row: 5, col: 4, letter: "T" }, { row: 5, col: 5, letter: "I" }, { row: 5, col: 6, letter: "R" }, { row: 5, col: 7, letter: "E" }, { row: 5, col: 8, letter: "D" },
    { row: 6, col: 0, letter: "A" }, { row: 6, col: 1, letter: "P" }, { row: 6, col: 2, letter: "E" }, { row: 6, col: 5, letter: "N" }, { row: 6, col: 6, letter: "O" }, { row: 6, col: 7, letter: "D" },
    { row: 7, col: 0, letter: "L" }, { row: 7, col: 1, letter: "O" }, { row: 7, col: 2, letter: "A" }, { row: 7, col: 3, letter: "D" }, { row: 7, col: 5, letter: "G" }, { row: 7, col: 6, letter: "O" }, { row: 7, col: 7, letter: "I" }, { row: 7, col: 8, letter: "N" }, { row: 7, col: 9, letter: "G" },
    { row: 8, col: 0, letter: "A" }, { row: 8, col: 1, letter: "L" }, { row: 8, col: 2, letter: "L" }, { row: 8, col: 3, letter: "O" }, { row: 8, col: 4, letter: "W" }, { row: 8, col: 6, letter: "S" }, { row: 8, col: 7, letter: "T" }, { row: 8, col: 8, letter: "O" }, { row: 8, col: 9, letter: "O" }, { row: 8, col: 10, letter: "P" },
    { row: 9, col: 0, letter: "S" }, { row: 9, col: 1, letter: "O" }, { row: 9, col: 2, letter: "L" }, { row: 9, col: 3, letter: "V" }, { row: 9, col: 4, letter: "E" }, { row: 9, col: 6, letter: "T" }, { row: 9, col: 7, letter: "O" }, { row: 9, col: 8, letter: "T" }, { row: 9, col: 9, letter: "A" }, { row: 9, col: 10, letter: "L" },
    { row: 10, col: 2, letter: "Y" }, { row: 10, col: 3, letter: "E" }, { row: 10, col: 4, letter: "T" }, { row: 10, col: 7, letter: "R" }, { row: 10, col: 8, letter: "E" }, { row: 10, col: 9, letter: "L" }, { row: 10, col: 10, letter: "Y" },
  ],
  clues: [
    { direction: "across", row: 0, col: 0, clueText: "Cook in an oven", segments: [4] },
    { direction: "down", row: 0, col: 0, clueText: "Place to sleep", segments: [3] },
    { direction: "down", row: 0, col: 1, clueText: "Tools for chopping wood", segments: [4] },
    { direction: "down", row: 0, col: 2, clueText: "Pleated tartan garment from the Highlands", segments: [4] },
    { direction: "down", row: 0, col: 3, clueText: "Large country property", segments: [6] },
    { direction: "across", row: 0, col: 6, clueText: "Slice", segments: [3] },
    { direction: "down", row: 0, col: 6, clueText: "Tin container", segments: [3] },
    { direction: "down", row: 0, col: 7, clueText: "Second-hand", segments: [4] },
    { direction: "down", row: 0, col: 8, clueText: "Cotton for sewing", segments: [6] },
    { direction: "across", row: 1, col: 0, clueText: "Be alive", segments: [5] },
    { direction: "down", row: 1, col: 4, clueText: "Cards used for fortune-telling", segments: [5] },
    { direction: "across", row: 1, col: 6, clueText: "Pale, like a startled face", segments: [5] },
    { direction: "down", row: 1, col: 9, clueText: "Level, or flat", segments: [4] },
    { direction: "down", row: 1, col: 10, clueText: "Bookish type, or swot", segments: [4] },
    { direction: "across", row: 2, col: 0, clueText: "Fourth letter of the Greek alphabet", segments: [5] },
    { direction: "across", row: 2, col: 6, clueText: "Courage, or a fibre that carries signals", segments: [5] },
    { direction: "across", row: 3, col: 1, clueText: "Begin", segments: [5] },
    { direction: "down", row: 3, col: 5, clueText: "Knotting a shoelace", segments: [5] },
    { direction: "across", row: 3, col: 7, clueText: "Animal with antlers", segments: [4] },
    { direction: "across", row: 4, col: 3, clueText: "Plaything", segments: [3] },
    { direction: "across", row: 4, col: 8, clueText: "Also, or plus", segments: [3] },
    { direction: "across", row: 5, col: 2, clueText: "No longer working", segments: [7] },
    { direction: "down", row: 5, col: 2, clueText: "Truly", segments: [6] },
    { direction: "down", row: 5, col: 6, clueText: "Perch where birds sleep", segments: [5] },
    { direction: "down", row: 5, col: 7, clueText: "One who corrects the text", segments: [6] },
    { direction: "across", row: 6, col: 0, clueText: "Primate, or to mimic", segments: [3] },
    { direction: "down", row: 6, col: 0, clueText: "Cry of sorrow", segments: [4] },
    { direction: "down", row: 6, col: 1, clueText: "Game played on horseback", segments: [4] },
    { direction: "across", row: 6, col: 5, clueText: "Silent sign of agreement", segments: [3] },
    { direction: "across", row: 7, col: 0, clueText: "Cargo", segments: [4] },
    { direction: "down", row: 7, col: 3, clueText: "Symbol of peace", segments: [4] },
    { direction: "across", row: 7, col: 5, clueText: "Leaving", segments: [5] },
    { direction: "down", row: 7, col: 8, clueText: "Short written message", segments: [4] },
    { direction: "down", row: 7, col: 9, clueText: "What a striker scores", segments: [4] },
    { direction: "across", row: 8, col: 0, clueText: "Permit", segments: [5] },
    { direction: "down", row: 8, col: 4, clueText: "Not dry", segments: [3] },
    { direction: "across", row: 8, col: 6, clueText: "Bend forward", segments: [5] },
    { direction: "down", row: 8, col: 10, clueText: "Strand in a rope", segments: [3] },
    { direction: "across", row: 9, col: 0, clueText: "Work out the answer to", segments: [5] },
    { direction: "across", row: 9, col: 6, clueText: "Sum", segments: [5] },
    { direction: "across", row: 10, col: 2, clueText: "Up to now", segments: [3] },
    { direction: "across", row: 10, col: 7, clueText: "Depend", segments: [4] },
  ],
} satisfies Content;
