import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/crossword/schema";

export const meta = {
  slug: "pencil-case",
  title: "Pencil Case",
  difficulty: 1,
  publishedAt: new Date("2026-10-01T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  style: "quick",
  rows: 11,
  cols: 11,
  cells: [
    { row: 0, col: 1, letter: "O" }, { row: 0, col: 2, letter: "G" }, { row: 0, col: 3, letter: "R" }, { row: 0, col: 4, letter: "E" }, { row: 0, col: 8, letter: "T" }, { row: 0, col: 9, letter: "A" }, { row: 0, col: 10, letter: "G" },
    { row: 1, col: 0, letter: "S" }, { row: 1, col: 1, letter: "P" }, { row: 1, col: 2, letter: "R" }, { row: 1, col: 3, letter: "A" }, { row: 1, col: 4, letter: "Y" }, { row: 1, col: 8, letter: "A" }, { row: 1, col: 9, letter: "W" }, { row: 1, col: 10, letter: "E" },
    { row: 2, col: 0, letter: "H" }, { row: 2, col: 1, letter: "E" }, { row: 2, col: 2, letter: "A" }, { row: 2, col: 3, letter: "T" }, { row: 2, col: 4, letter: "E" }, { row: 2, col: 5, letter: "R" }, { row: 2, col: 7, letter: "S" }, { row: 2, col: 8, letter: "P" }, { row: 2, col: 9, letter: "A" }, { row: 2, col: 10, letter: "N" },
    { row: 3, col: 0, letter: "I" }, { row: 3, col: 1, letter: "R" }, { row: 3, col: 2, letter: "I" }, { row: 3, col: 3, letter: "S" }, { row: 3, col: 5, letter: "E" }, { row: 3, col: 6, letter: "N" }, { row: 3, col: 7, letter: "T" }, { row: 3, col: 8, letter: "I" }, { row: 3, col: 9, letter: "R" }, { row: 3, col: 10, letter: "E" },
    { row: 4, col: 0, letter: "P" }, { row: 4, col: 1, letter: "A" }, { row: 4, col: 2, letter: "N" }, { row: 4, col: 5, letter: "G" }, { row: 4, col: 6, letter: "U" }, { row: 4, col: 7, letter: "A" }, { row: 4, col: 8, letter: "R" }, { row: 4, col: 9, letter: "D" },
    { row: 5, col: 3, letter: "S" }, { row: 5, col: 4, letter: "W" }, { row: 5, col: 5, letter: "U" }, { row: 5, col: 6, letter: "N" }, { row: 5, col: 7, letter: "G" },
    { row: 6, col: 1, letter: "P" }, { row: 6, col: 2, letter: "U" }, { row: 6, col: 3, letter: "P" }, { row: 6, col: 4, letter: "I" }, { row: 6, col: 5, letter: "L" }, { row: 6, col: 8, letter: "L" }, { row: 6, col: 9, letter: "A" }, { row: 6, col: 10, letter: "W" },
    { row: 7, col: 0, letter: "B" }, { row: 7, col: 1, letter: "A" }, { row: 7, col: 2, letter: "N" }, { row: 7, col: 3, letter: "A" }, { row: 7, col: 4, letter: "N" }, { row: 7, col: 5, letter: "A" }, { row: 7, col: 7, letter: "S" }, { row: 7, col: 8, letter: "A" }, { row: 7, col: 9, letter: "G" }, { row: 7, col: 10, letter: "A" },
    { row: 8, col: 0, letter: "E" }, { row: 8, col: 1, letter: "L" }, { row: 8, col: 2, letter: "M" }, { row: 8, col: 3, letter: "S" }, { row: 8, col: 5, letter: "R" }, { row: 8, col: 6, letter: "E" }, { row: 8, col: 7, letter: "A" }, { row: 8, col: 8, letter: "D" }, { row: 8, col: 9, letter: "E" }, { row: 8, col: 10, letter: "R" },
    { row: 9, col: 0, letter: "T" }, { row: 9, col: 1, letter: "E" }, { row: 9, col: 2, letter: "E" }, { row: 9, col: 6, letter: "E" }, { row: 9, col: 7, letter: "V" }, { row: 9, col: 8, letter: "E" }, { row: 9, col: 9, letter: "N" }, { row: 9, col: 10, letter: "T" },
    { row: 10, col: 0, letter: "A" }, { row: 10, col: 1, letter: "R" }, { row: 10, col: 2, letter: "T" }, { row: 10, col: 6, letter: "L" }, { row: 10, col: 7, letter: "E" }, { row: 10, col: 8, letter: "N" }, { row: 10, col: 9, letter: "T" },
  ],
  clues: [
    { direction: "across", row: 0, col: 1, clueText: "Fairy-tale monster with a taste for human dinners", segments: [4] },
    { direction: "down", row: 0, col: 1, clueText: "Stage work in which the plot is sung", segments: [5] },
    { direction: "down", row: 0, col: 2, clueText: "Wheat or barley, for example", segments: [5] },
    { direction: "down", row: 0, col: 3, clueText: "Scurrying pests of the sewer", segments: [4] },
    { direction: "down", row: 0, col: 4, clueText: "Organ that sees, or the calm centre of a storm", segments: [3] },
    { direction: "across", row: 0, col: 8, clueText: "Playground chasing game", segments: [3] },
    { direction: "down", row: 0, col: 8, clueText: "Long-nosed forest animal with hooves", segments: [5] },
    { direction: "down", row: 0, col: 9, clueText: "Prize", segments: [5] },
    { direction: "down", row: 0, col: 10, clueText: "Unit of heredity", segments: [4] },
    { direction: "across", row: 1, col: 0, clueText: "Fine mist from an aerosol can", segments: [5] },
    { direction: "down", row: 1, col: 0, clueText: "Large vessel at sea", segments: [4] },
    { direction: "across", row: 1, col: 8, clueText: "Wonder mixed with fear", segments: [3] },
    { direction: "across", row: 2, col: 0, clueText: "Appliance that warms a room", segments: [6] },
    { direction: "down", row: 2, col: 5, clueText: "Customer who comes in all the time", segments: [7] },
    { direction: "across", row: 2, col: 7, clueText: "Stretch across, as a bridge does", segments: [4] },
    { direction: "down", row: 2, col: 7, clueText: "Male deer", segments: [4] },
    { direction: "across", row: 3, col: 0, clueText: "Garden flower named after the Greek goddess of the rainbow", segments: [4] },
    { direction: "across", row: 3, col: 5, clueText: "Whole", segments: [6] },
    { direction: "down", row: 3, col: 6, clueText: "Woman who lives in a convent", segments: [3] },
    { direction: "across", row: 4, col: 0, clueText: "Frying vessel", segments: [3] },
    { direction: "across", row: 4, col: 5, clueText: "Sentry on duty", segments: [5] },
    { direction: "across", row: 5, col: 3, clueText: "Moved back and forth, like a pendulum", segments: [5] },
    { direction: "down", row: 5, col: 3, clueText: "Health resorts with hot springs", segments: [4] },
    { direction: "down", row: 5, col: 4, clueText: "Come first", segments: [3] },
    { direction: "across", row: 6, col: 1, clueText: "One taught by a teacher", segments: [5] },
    { direction: "down", row: 6, col: 1, clueText: "Whiter, as a ghost", segments: [5] },
    { direction: "down", row: 6, col: 2, clueText: "Not satisfied, as a need", segments: [5] },
    { direction: "across", row: 6, col: 8, clueText: "Rule enforced by the courts", segments: [3] },
    { direction: "down", row: 6, col: 8, clueText: "Heavily loaded", segments: [5] },
    { direction: "down", row: 6, col: 9, clueText: "Representative, or secret spy", segments: [5] },
    { direction: "down", row: 6, col: 10, clueText: "Small hard growth on the skin", segments: [4] },
    { direction: "across", row: 7, col: 0, clueText: "Yellow fruit that grows in a bunch", segments: [6] },
    { direction: "down", row: 7, col: 0, clueText: "Second Greek letter", segments: [4] },
    { direction: "across", row: 7, col: 7, clueText: "Long story of heroic deeds", segments: [4] },
    { direction: "down", row: 7, col: 7, clueText: "Rescue, or put money aside", segments: [4] },
    { direction: "across", row: 8, col: 0, clueText: "Tall trees along an avenue", segments: [4] },
    { direction: "across", row: 8, col: 5, clueText: "Person with a book in hand", segments: [6] },
    { direction: "down", row: 8, col: 6, clueText: "Slippery snake-like fish", segments: [3] },
    { direction: "across", row: 9, col: 0, clueText: "Golf peg", segments: [3] },
    { direction: "across", row: 9, col: 6, clueText: "Happening", segments: [5] },
    { direction: "across", row: 10, col: 0, clueText: "What a gallery hangs on its walls", segments: [3] },
    { direction: "across", row: 10, col: 6, clueText: "Handed over for a while", segments: [4] },
  ],
} satisfies Content;
