import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/crossword/schema";

export const meta = {
  slug: "red-herring",
  title: "Red Herring",
  difficulty: 3,
  publishedAt: new Date("2026-10-03T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  style: "cryptic",
  rows: 13,
  cols: 13,
  cells: [
    { row: 0, col: 0, letter: "B" }, { row: 0, col: 1, letter: "E" }, { row: 0, col: 2, letter: "S" }, { row: 0, col: 3, letter: "I" }, { row: 0, col: 4, letter: "D" }, { row: 0, col: 5, letter: "E" }, { row: 0, col: 7, letter: "C" }, { row: 0, col: 8, letter: "A" }, { row: 0, col: 9, letter: "N" }, { row: 0, col: 10, letter: "V" }, { row: 0, col: 11, letter: "A" }, { row: 0, col: 12, letter: "S" },
    { row: 1, col: 0, letter: "A" }, { row: 1, col: 2, letter: "O" }, { row: 1, col: 4, letter: "O" }, { row: 1, col: 6, letter: "E" }, { row: 1, col: 8, letter: "L" }, { row: 1, col: 10, letter: "E" }, { row: 1, col: 12, letter: "Y" },
    { row: 2, col: 0, letter: "N" }, { row: 2, col: 1, letter: "I" }, { row: 2, col: 2, letter: "N" }, { row: 2, col: 3, letter: "E" }, { row: 2, col: 4, letter: "L" }, { row: 2, col: 5, letter: "I" }, { row: 2, col: 6, letter: "V" }, { row: 2, col: 7, letter: "E" }, { row: 2, col: 8, letter: "S" }, { row: 2, col: 10, letter: "H" }, { row: 2, col: 11, letter: "U" }, { row: 2, col: 12, letter: "M" },
    { row: 3, col: 0, letter: "A" }, { row: 3, col: 2, letter: "A" }, { row: 3, col: 4, letter: "P" }, { row: 3, col: 6, letter: "E" }, { row: 3, col: 8, letter: "O" }, { row: 3, col: 10, letter: "I" }, { row: 3, col: 12, letter: "B" },
    { row: 4, col: 0, letter: "N" }, { row: 4, col: 1, letter: "O" }, { row: 4, col: 2, letter: "R" }, { row: 4, col: 3, letter: "T" }, { row: 4, col: 4, letter: "H" }, { row: 4, col: 5, letter: "E" }, { row: 4, col: 6, letter: "R" }, { row: 4, col: 7, letter: "N" }, { row: 4, col: 9, letter: "E" }, { row: 4, col: 10, letter: "C" }, { row: 4, col: 11, letter: "H" }, { row: 4, col: 12, letter: "O" },
    { row: 5, col: 0, letter: "A" }, { row: 5, col: 4, letter: "I" }, { row: 5, col: 6, letter: "Y" }, { row: 5, col: 8, letter: "H" }, { row: 5, col: 10, letter: "L" }, { row: 5, col: 12, letter: "L" },
    { row: 6, col: 1, letter: "P" }, { row: 6, col: 2, letter: "O" }, { row: 6, col: 3, letter: "U" }, { row: 6, col: 4, letter: "N" }, { row: 6, col: 5, letter: "D" }, { row: 6, col: 7, letter: "W" }, { row: 6, col: 8, letter: "A" }, { row: 6, col: 9, letter: "T" }, { row: 6, col: 10, letter: "E" }, { row: 6, col: 11, letter: "R" },
    { row: 7, col: 0, letter: "S" }, { row: 7, col: 2, letter: "B" }, { row: 7, col: 4, letter: "S" }, { row: 7, col: 6, letter: "L" }, { row: 7, col: 8, letter: "R" }, { row: 7, col: 12, letter: "B" },
    { row: 8, col: 0, letter: "H" }, { row: 8, col: 1, letter: "A" }, { row: 8, col: 2, letter: "V" }, { row: 8, col: 3, letter: "E" }, { row: 8, col: 5, letter: "H" }, { row: 8, col: 6, letter: "A" }, { row: 8, col: 7, letter: "N" }, { row: 8, col: 8, letter: "D" }, { row: 8, col: 9, letter: "O" }, { row: 8, col: 10, letter: "V" }, { row: 8, col: 11, letter: "E" }, { row: 8, col: 12, letter: "R" },
    { row: 9, col: 0, letter: "O" }, { row: 9, col: 2, letter: "I" }, { row: 9, col: 4, letter: "M" }, { row: 9, col: 6, letter: "T" }, { row: 9, col: 8, letter: "C" }, { row: 9, col: 10, letter: "O" }, { row: 9, col: 12, letter: "I" },
    { row: 10, col: 0, letter: "W" }, { row: 10, col: 1, letter: "H" }, { row: 10, col: 2, letter: "O" }, { row: 10, col: 4, letter: "E" }, { row: 10, col: 5, letter: "N" }, { row: 10, col: 6, letter: "C" }, { row: 10, col: 7, letter: "H" }, { row: 10, col: 8, letter: "A" }, { row: 10, col: 9, letter: "N" }, { row: 10, col: 10, letter: "T" }, { row: 10, col: 11, letter: "E" }, { row: 10, col: 12, letter: "D" },
    { row: 11, col: 0, letter: "E" }, { row: 11, col: 2, letter: "U" }, { row: 11, col: 4, letter: "N" }, { row: 11, col: 6, letter: "H" }, { row: 11, col: 8, letter: "S" }, { row: 11, col: 10, letter: "E" }, { row: 11, col: 12, letter: "G" },
    { row: 12, col: 0, letter: "R" }, { row: 12, col: 1, letter: "E" }, { row: 12, col: 2, letter: "S" }, { row: 12, col: 3, letter: "C" }, { row: 12, col: 4, letter: "U" }, { row: 12, col: 5, letter: "E" }, { row: 12, col: 7, letter: "C" }, { row: 12, col: 8, letter: "H" }, { row: 12, col: 9, letter: "A" }, { row: 12, col: 10, letter: "R" }, { row: 12, col: 11, letter: "G" }, { row: 12, col: 12, letter: "E" },
  ],
  clues: [
    { direction: "across", row: 0, col: 0, clueText: "Exist with squad alongside", segments: [6] },
    { direction: "down", row: 0, col: 0, clueText: "Born, a nan, and a yellow fruit", segments: [6] },
    { direction: "down", row: 0, col: 2, clueText: "Boy getting a right underwater detector", segments: [5] },
    { direction: "down", row: 0, col: 4, clueText: "Hold pins, wildly, for sea mammals", segments: [8] },
    { direction: "across", row: 0, col: 7, clueText: "Seek votes, shedding second, for tent material", segments: [6] },
    { direction: "down", row: 0, col: 8, clueText: "A London orchestra as well", segments: [4] },
    { direction: "down", row: 0, col: 10, clueText: "Transport, or means of expression", segments: [7] },
    { direction: "down", row: 0, col: 12, clueText: "Sly mob rioting, producing an emblem", segments: [6] },
    { direction: "down", row: 1, col: 6, clueText: "English, extremely, for each", segments: [5] },
    { direction: "across", row: 2, col: 0, clueText: "Cat's allowance: number resides", segments: [4, 5] },
    { direction: "across", row: 2, col: 10, clueText: "Drone found in thumbs", segments: [3] },
    { direction: "across", row: 4, col: 0, clueText: "Rent horn wrecked, like the Geordies", segments: [8] },
    { direction: "across", row: 4, col: 9, clueText: "Reverberation after Delta in phonetic alphabet", segments: [4] },
    { direction: "down", row: 5, col: 8, clueText: "Notes and coins: tough dosh", segments: [4, 4] },
    { direction: "across", row: 6, col: 1, clueText: "Beat sterling", segments: [5] },
    { direction: "down", row: 6, col: 2, clueText: "Clear: died, six, round and us", segments: [7] },
    { direction: "across", row: 6, col: 7, clueText: "Waiter losing one gets drink", segments: [5] },
    { direction: "down", row: 7, col: 0, clueText: "Wet spell, or exhibitor", segments: [6] },
    { direction: "down", row: 7, col: 6, clueText: "Door fastener: latitude briefly, with church", segments: [5] },
    { direction: "down", row: 7, col: 12, clueText: "Game, or span", segments: [6] },
    { direction: "across", row: 8, col: 0, clueText: "Husband's Roman salute: to possess", segments: [4] },
    { direction: "across", row: 8, col: 5, clueText: "Help that's finished: it's a transfer", segments: [8] },
    { direction: "down", row: 8, col: 10, clueText: "Overt transformed into elector", segments: [5] },
    { direction: "down", row: 9, col: 4, clueText: "Men with university list of dishes", segments: [4] },
    { direction: "across", row: 10, col: 0, clueText: "Doctor, perhaps, as question of identity", segments: [3] },
    { direction: "across", row: 10, col: 4, clueText: "Dance then differently, being under a spell", segments: [9] },
    { direction: "across", row: 12, col: 0, clueText: "Concerning second prompt to save", segments: [6] },
    { direction: "across", row: 12, col: 7, clueText: "Cost, or rush into battle", segments: [6] },
  ],
} satisfies Content;
