import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/crossword/schema";

export const meta = {
  slug: "second-draft",
  title: "Second Draft",
  difficulty: 2,
  publishedAt: new Date("2026-10-01T00:00:00Z"),
} satisfies ContentMeta;

export const content = {
  style: "quick",
  rows: 11,
  cols: 11,
  cells: [
    { row: 0, col: 0, letter: "C" }, { row: 0, col: 1, letter: "A" }, { row: 0, col: 2, letter: "R" }, { row: 0, col: 6, letter: "A" }, { row: 0, col: 7, letter: "C" }, { row: 0, col: 8, letter: "H" }, { row: 0, col: 9, letter: "E" },
    { row: 1, col: 0, letter: "A" }, { row: 1, col: 1, letter: "R" }, { row: 1, col: 2, letter: "E" }, { row: 1, col: 3, letter: "A" }, { row: 1, col: 6, letter: "C" }, { row: 1, col: 7, letter: "H" }, { row: 1, col: 8, letter: "E" }, { row: 1, col: 9, letter: "A" }, { row: 1, col: 10, letter: "T" },
    { row: 2, col: 0, letter: "B" }, { row: 2, col: 1, letter: "R" }, { row: 2, col: 2, letter: "A" }, { row: 2, col: 3, letter: "N" }, { row: 2, col: 4, letter: "D" }, { row: 2, col: 6, letter: "E" }, { row: 2, col: 7, letter: "A" }, { row: 2, col: 8, letter: "R" }, { row: 2, col: 9, letter: "T" }, { row: 2, col: 10, letter: "H" },
    { row: 3, col: 0, letter: "L" }, { row: 3, col: 1, letter: "A" }, { row: 3, col: 2, letter: "D" }, { row: 3, col: 3, letter: "D" }, { row: 3, col: 4, letter: "E" }, { row: 3, col: 5, letter: "R" }, { row: 3, col: 7, letter: "P" }, { row: 3, col: 8, letter: "O" }, { row: 3, col: 9, letter: "S" }, { row: 3, col: 10, letter: "E" },
    { row: 4, col: 0, letter: "E" }, { row: 4, col: 1, letter: "Y" }, { row: 4, col: 2, letter: "E" }, { row: 4, col: 4, letter: "R" }, { row: 4, col: 5, letter: "O" }, { row: 4, col: 6, letter: "P" }, { row: 4, col: 7, letter: "E" },
    { row: 5, col: 2, letter: "R" }, { row: 5, col: 3, letter: "E" }, { row: 5, col: 4, letter: "B" }, { row: 5, col: 5, letter: "U" }, { row: 5, col: 6, letter: "I" }, { row: 5, col: 7, letter: "L" }, { row: 5, col: 8, letter: "D" },
    { row: 6, col: 3, letter: "L" }, { row: 6, col: 4, letter: "Y" }, { row: 6, col: 5, letter: "N" }, { row: 6, col: 6, letter: "X" }, { row: 6, col: 8, letter: "R" }, { row: 6, col: 9, letter: "A" }, { row: 6, col: 10, letter: "T" },
    { row: 7, col: 0, letter: "A" }, { row: 7, col: 1, letter: "C" }, { row: 7, col: 2, letter: "R" }, { row: 7, col: 3, letter: "E" }, { row: 7, col: 5, letter: "D" }, { row: 7, col: 6, letter: "E" }, { row: 7, col: 7, letter: "S" }, { row: 7, col: 8, letter: "I" }, { row: 7, col: 9, letter: "R" }, { row: 7, col: 10, letter: "E" },
    { row: 8, col: 0, letter: "C" }, { row: 8, col: 1, letter: "R" }, { row: 8, col: 2, letter: "A" }, { row: 8, col: 3, letter: "V" }, { row: 8, col: 4, letter: "E" }, { row: 8, col: 6, letter: "L" }, { row: 8, col: 7, letter: "I" }, { row: 8, col: 8, letter: "V" }, { row: 8, col: 9, letter: "E" }, { row: 8, col: 10, letter: "D" },
    { row: 9, col: 0, letter: "T" }, { row: 9, col: 1, letter: "A" }, { row: 9, col: 2, letter: "K" }, { row: 9, col: 3, letter: "E" }, { row: 9, col: 4, letter: "N" }, { row: 9, col: 7, letter: "T" }, { row: 9, col: 8, letter: "E" }, { row: 9, col: 9, letter: "N" }, { row: 9, col: 10, letter: "D" },
    { row: 10, col: 1, letter: "B" }, { row: 10, col: 2, letter: "E" }, { row: 10, col: 3, letter: "N" }, { row: 10, col: 4, letter: "D" }, { row: 10, col: 8, letter: "R" }, { row: 10, col: 9, letter: "A" }, { row: 10, col: 10, letter: "Y" },
  ],
  clues: [
    { direction: "across", row: 0, col: 0, clueText: "Vehicle that might be parked on a drive", segments: [3] },
    { direction: "down", row: 0, col: 0, clueText: "Thick wire, or an old-fashioned telegram", segments: [5] },
    { direction: "down", row: 0, col: 1, clueText: "Impressive display or range", segments: [5] },
    { direction: "down", row: 0, col: 2, clueText: "One engrossed in a novel", segments: [6] },
    { direction: "across", row: 0, col: 6, clueText: "Dull pain", segments: [4] },
    { direction: "down", row: 0, col: 6, clueText: "Top card, or an unreturnable serve", segments: [3] },
    { direction: "down", row: 0, col: 7, clueText: "Small place of worship", segments: [6] },
    { direction: "down", row: 0, col: 8, clueText: "Brave person who saves the day", segments: [4] },
    { direction: "down", row: 0, col: 9, clueText: "Has a meal", segments: [4] },
    { direction: "across", row: 1, col: 0, clueText: "Region", segments: [4] },
    { direction: "down", row: 1, col: 3, clueText: "Conjunction that joins", segments: [3] },
    { direction: "across", row: 1, col: 6, clueText: "Break the rules to win", segments: [5] },
    { direction: "down", row: 1, col: 10, clueText: "Definite article", segments: [3] },
    { direction: "across", row: 2, col: 0, clueText: "Make of goods, or to mark with a hot iron", segments: [5] },
    { direction: "down", row: 2, col: 4, clueText: "Bowler hat, or a famous race at Epsom", segments: [5] },
    { direction: "across", row: 2, col: 6, clueText: "Our planet", segments: [5] },
    { direction: "across", row: 3, col: 0, clueText: "Rungs for climbing", segments: [6] },
    { direction: "down", row: 3, col: 5, clueText: "Circular, or a drink for everyone at the bar", segments: [5] },
    { direction: "across", row: 3, col: 7, clueText: "Sit for a portrait", segments: [4] },
    { direction: "across", row: 4, col: 0, clueText: "Needle's hole, or organ of sight", segments: [3] },
    { direction: "across", row: 4, col: 4, clueText: "Thick cord", segments: [4] },
    { direction: "down", row: 4, col: 6, clueText: "Dot on a screen", segments: [5] },
    { direction: "across", row: 5, col: 2, clueText: "Construct again", segments: [7] },
    { direction: "down", row: 5, col: 3, clueText: "Players in a football team", segments: [6] },
    { direction: "down", row: 5, col: 8, clueText: "One at the wheel", segments: [6] },
    { direction: "across", row: 6, col: 3, clueText: "Wild cat with tufted ears", segments: [4] },
    { direction: "across", row: 6, col: 8, clueText: "Traitor, or a rodent", segments: [3] },
    { direction: "down", row: 6, col: 9, clueText: "Stadium", segments: [5] },
    { direction: "down", row: 6, col: 10, clueText: "Cuddly toy bear", segments: [5] },
    { direction: "across", row: 7, col: 0, clueText: "Land measure", segments: [4] },
    { direction: "down", row: 7, col: 0, clueText: "Do something on stage", segments: [3] },
    { direction: "down", row: 7, col: 1, clueText: "Sideways-walking shellfish", segments: [4] },
    { direction: "down", row: 7, col: 2, clueText: "Tool for gathering leaves", segments: [4] },
    { direction: "across", row: 7, col: 5, clueText: "Strong wish", segments: [6] },
    { direction: "down", row: 7, col: 7, clueText: "Take a chair", segments: [3] },
    { direction: "across", row: 8, col: 0, clueText: "Long for", segments: [5] },
    { direction: "down", row: 8, col: 4, clueText: "Conclusion", segments: [3] },
    { direction: "across", row: 8, col: 6, clueText: "Resided", segments: [5] },
    { direction: "across", row: 9, col: 0, clueText: "Removed from a shelf, say", segments: [5] },
    { direction: "across", row: 9, col: 7, clueText: "Look after", segments: [4] },
    { direction: "across", row: 10, col: 1, clueText: "Curve in a road", segments: [4] },
    { direction: "across", row: 10, col: 8, clueText: "Beam of light, or a flat fish", segments: [3] },
  ],
} satisfies Content;
