import type { ContentMeta } from "../../scripts/content-files";
import type { Content } from "../../src/puzzles/reverse-chess/schema";

export const meta = {
  slug: "the-long-walk",
  title: "The Long Walk",
  difficulty: 5,
  sourceNote:
    "Original position, built from a proof game by the Ludwig authors.",
  publishedAt: new Date("2026-10-06T00:00:00Z"),
} satisfies ContentMeta;

/**
 * rn1qkbnr/p1p2ppp/8/1n1N4/8/8/1P1PPPPP/RNB1KBNR w KQkq - 3 8
 * Proof game: a4 d5 a5 d4 a6 d3 axb7 dxc2 bxc8=N cxd1=N Nxe7 Nc3 Nd5 Nb5
 */
export const content = {
  mode: "unwind",
  sideToMove: "white",
  whiteKingside: true,
  whiteQueenside: true,
  blackKingside: true,
  blackQueenside: true,
  halfmove: 3,
  fullmove: 8,
  goal: {
    kind: "initial_position",
    displayText: "Back to the starting position",
  },
  pieces: [
    { file: "a", rank: 8, colour: "black", piece: "rook" },
    { file: "b", rank: 8, colour: "black", piece: "knight" },
    { file: "d", rank: 8, colour: "black", piece: "queen" },
    { file: "e", rank: 8, colour: "black", piece: "king" },
    { file: "f", rank: 8, colour: "black", piece: "bishop" },
    { file: "g", rank: 8, colour: "black", piece: "knight" },
    { file: "h", rank: 8, colour: "black", piece: "rook" },
    { file: "a", rank: 7, colour: "black", piece: "pawn" },
    { file: "c", rank: 7, colour: "black", piece: "pawn" },
    { file: "f", rank: 7, colour: "black", piece: "pawn" },
    { file: "g", rank: 7, colour: "black", piece: "pawn" },
    { file: "h", rank: 7, colour: "black", piece: "pawn" },
    { file: "b", rank: 5, colour: "black", piece: "knight" },
    { file: "d", rank: 5, colour: "white", piece: "knight" },
    { file: "b", rank: 2, colour: "white", piece: "pawn" },
    { file: "d", rank: 2, colour: "white", piece: "pawn" },
    { file: "e", rank: 2, colour: "white", piece: "pawn" },
    { file: "f", rank: 2, colour: "white", piece: "pawn" },
    { file: "g", rank: 2, colour: "white", piece: "pawn" },
    { file: "h", rank: 2, colour: "white", piece: "pawn" },
    { file: "a", rank: 1, colour: "white", piece: "rook" },
    { file: "b", rank: 1, colour: "white", piece: "knight" },
    { file: "c", rank: 1, colour: "white", piece: "bishop" },
    { file: "e", rank: 1, colour: "white", piece: "king" },
    { file: "f", rank: 1, colour: "white", piece: "bishop" },
    { file: "g", rank: 1, colour: "white", piece: "knight" },
    { file: "h", rank: 1, colour: "white", piece: "rook" },
  ],
  solutionPlies: [
    {
      fromFile: "c",
      fromRank: 3,
      toFile: "b",
      toRank: 5,
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "e",
      fromRank: 7,
      toFile: "d",
      toRank: 5,
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "d",
      fromRank: 1,
      toFile: "c",
      toRank: 3,
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "c",
      fromRank: 8,
      toFile: "e",
      toRank: 7,
      uncapture: "pawn",
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "c",
      fromRank: 2,
      toFile: "d",
      toRank: 1,
      uncapture: "queen",
      unpromote: true,
      special: "none",
    },
    {
      fromFile: "b",
      fromRank: 7,
      toFile: "c",
      toRank: 8,
      uncapture: "bishop",
      unpromote: true,
      special: "none",
    },
    {
      fromFile: "d",
      fromRank: 3,
      toFile: "c",
      toRank: 2,
      uncapture: "pawn",
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "a",
      fromRank: 6,
      toFile: "b",
      toRank: 7,
      uncapture: "pawn",
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "d",
      fromRank: 4,
      toFile: "d",
      toRank: 3,
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "a",
      fromRank: 5,
      toFile: "a",
      toRank: 6,
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "d",
      fromRank: 5,
      toFile: "d",
      toRank: 4,
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "a",
      fromRank: 4,
      toFile: "a",
      toRank: 5,
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "d",
      fromRank: 7,
      toFile: "d",
      toRank: 5,
      unpromote: false,
      special: "none",
    },
    {
      fromFile: "a",
      fromRank: 2,
      toFile: "a",
      toRank: 4,
      unpromote: false,
      special: "none",
    },
  ],
} satisfies Content;
